name: Run Jest Tests with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests with Selenium
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Create .env
        run: |
          touch .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "OPENAI_MODEL=${{ vars.OPENAI_MODEL }}" >> .env
          echo "URL_NEWS=${{ vars.URL_NEWS }}" >> .env
 
      - name: Install Dependencies
        run: npm install  

      - name: Run Jest Tests
        run: npm test

      - name: Stop Selenium Services
        run: docker stop $(docker ps -q)
